#!/bin/bash
set -u

# ==============================================================================
# Use the following workflow:
#
#   1. Log into the Xorg version of gnome-shell to enable shell restarts.
#   2. Run this script at least once and each time you edit the data files.
#   3. Run './scripts/listen' to listen for runtime errors.
#   4. Run 'tsc --watch' for typechecking and recompilation.
#   6. Run './scripts/restart' after modifiying source files.
# ==============================================================================
cd "${BASH_SOURCE%/*}/.."

uuid="cronomix@zagortenay333"
ext_dir=~/".local/share/gnome-shell/extensions/${uuid}"

# ==============================================================================
# Build tsconfig.json file
# ==============================================================================
#
cat > "tsconfig.json" << EOF
{
    "include": [ "src/**/*" ],
    "compilerOptions": {
        "target": "es2022",
        "lib": [ "es2022" ],
        "outDir": "$ext_dir",
        "strict": true,
        "pretty": true,
        "incremental": true,
        "noUnusedLocals": true,
        "noImplicitReturns": true,
        "noUnusedParameters": true,
        "downlevelIteration": true,
        "skipDefaultLibCheck": true,
        "exactOptionalPropertyTypes": true,
        "forceConsistentCasingInFileNames": true
    }
}
EOF

# ==============================================================================
# Build data
# ==============================================================================
rm -rf "$ext_dir"
mkdir -p "$ext_dir/data"

cp -r "data/docs" "$ext_dir/data/docs"
cp -r "data/sounds" "$ext_dir/data/sounds"
cp -r "data/themes" "$ext_dir/data/themes"
cp -r "data/images/icons" "$ext_dir/data/icons"
cp -r "data/metadata.json" "$ext_dir/metadata.json"

# ==============================================================================
# Build translation files
# ==============================================================================
mo_dir="$ext_dir/locale"
po_dir="data/translations"
po_files=$(find "$po_dir" -name "*.po")
template="data/translations/template.pot"

find "src" -type f -name "*.ts" |
    xgettext --no-location --language=JavaScript --from-code=UTF-8 --add-comments="TRANSLATORS:" -o "$template" -f -

for po_file in $po_files; do
    msgmerge --quiet -U "$po_file" --backup="none" "$template"
    msgattrib --output-file="$po_file" --no-obsolete "$po_file"
    lang=${po_file##*/}
    lang=${lang%.*}
    mkdir -p "$mo_dir/$lang/LC_MESSAGES/"
	msgfmt "$po_dir/$lang.po" -o "$mo_dir/$lang/LC_MESSAGES/cronomix.mo"
done
