#!/bin/bash
set -u

cd "${BASH_SOURCE%/*}/.."

proj_dir=$(pwd)
uuid="cronomix@zagortenay333"
ext_dir=~/".local/share/gnome-shell/extensions/${uuid}"

# ==============================================================================
# In order to preserve blank lines in the emitted
# js files, we replace blanks in the typescript
# files with a special comment before we invoke
# the compiler.
#
# The compiler preserves comments even though it
# apparently can't to the same with newlines...
# ==============================================================================
for input in $(find src -name '*.ts'); do
    sed -z -i 's;\n\n;\n/\*234h1764d7482a3a\*/\n;g' $input
done

# ==============================================================================
# Compile.
# ==============================================================================
./scripts/build
tsc
wait

# ==============================================================================
# Now replace the special comment with a blank line
# both in the typescript and the emitted js files.
# ==============================================================================
for input in $(find src -name '*.ts'); do
    sed -i 's;/\*234h1764d7482a3a\*/;;g' $input
done

sleep 10
wait

for input in $(find $ext_dir -name '*.js'); do
    sed -i 's;/\*234h1764d7482a3a\*/;;g' $input
done

wait

# ==============================================================================
# Finish up.
# ==============================================================================
cd "$ext_dir"
rm tsconfig.tsbuildinfo
rm "$proj_dir/data/$uuid.zip"
zip -q -r "$proj_dir/data/$uuid.zip" .
